mixed-port: 7899
allow-lan: false
mode: rule
log-level: info
ipv6: false
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
external-controller: 127.0.0.1:9090
profile:
  store-selected: false
  store-fake-ip: false
proxies: []
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - REJECT
listeners:
- name: Proxy-in
  type: mixed
  listen: 127.0.0.1
  port: 7894
  proxy: Proxy
rules:
- MATCH,Proxy
