proxy:
  listen_host: 127.0.0.1
  listen_port: 18000
  receiver_port: 17890
auto_select:
  check_interval: 20
  max_fail_count: 2
  delay_timeout_ms: 1000
  test_url: http://www.google.com/generate_204
mihomo:
  exe: ''
  controller_port: 9090
  mixed_port: 7899
ui:
  close_to_tray: true
  start_minimized: false
  auto_start_proxy: false
  enable_system_proxy_on_start: true
  disable_system_proxy_on_stop: true
updated_at: '2026-05-24 06:13:28'
